### ISSUE TITLE
Bug in the code snippet for `wayland_handle_message` in wayland article   

### ISSUE THREAD

**Issue by umurgdk** [gaultier/blog#15]
I think this line should check the `announced_size` against the `msg_len` directly without adding `header_size` since the `announced_size` is the sum of the header and the rest of the message. Therefore this line should be:

```c
assert(announced_size <= *msg_len);
``` 

https://github.com/gaultier/blog/blob/17b871185fb75e3381d26fa9938b3289a09279d3/wayland_from_scratch.md?plain=1#L414

Another bug on the same function (next code snippet) is the assertion of the interface string `NUL` terminator. Reported string length includes the `NUL` terminator as well. And when the string buffer is padded to 4 bytes after the `NUL` should be considered garbage according to specification. Therefore it should be:

```c
assert(interface[interface_len - 1] == 0);
```

https://github.com/gaultier/blog/blob/17b871185fb75e3381d26fa9938b3289a09279d3/wayland_from_scratch.md?plain=1#L446

**Comment by gaultier** [comment]
Thank you for the report.
For the first point, I think the current code is correct. That's because the helper functions `buf_read_xxx` decrement the message size as they read (they act like a cursor), so when we reach this line, the 'read cursor' is right past the header (of size 8), and `*msg_len` is the remaining length (e.g., 12), but the announced size is `8 + 12 = 20`.
As seen in the debugger:
![image](https://github.com/user-attachments/assets/bd69c4aa-3991-4ad2-a2b7-15fb8c5cc520)

For the second point, I believe you are right, since the spec says:
> Starts with an unsigned 32-bit length (including null terminator),

**Comment by umurgdk** [comment]
Oh I didn’t notice the readers were mutating msg_len as well sorry about
that.

**Comment by gaultier** [comment]
Fixed in https://github.com/gaultier/blog/commit/5f0ae3c4e8ce9b619d7bcd65d37bee32e7158272.
Thank you!
